# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
     types: [opened, edited, reopened, synchronize]
     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: cddockertest.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Maven Package
        run:  cd complete/ && mvn clean package && mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
        
      - name: Docker Build
        run: |
          cd complete/
          docker build . -t cddockertest.azurecr.io/gs-spring-boot-docker:${{ github.sha }}
          docker push cddockertest.azurecr.io/gs-spring-boot-docker:${{ github.sha }}
        
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'tf-test-webapp'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'cddockertest.azurecr.io/gs-spring-boot-docker:${{ github.sha }}'
